# Generated by Django 4.1.7 on 2023-02-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="anime",
            name="title",
            field=models.CharField(default="", max_length=80),
        ),
    ]
